//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Medical_Test = new HashSet<Medical_Test>();
        }
    
        public int appointment_id { get; set; }
        public System.DateTime appointment_date { get; set; }
        public System.TimeSpan Appointment_time { get; set; }
        public string appointment_type { get; set; }
        public int Venue_id { get; set; }
        public int Patient_id { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Test> Medical_Test { get; set; }
    }
}
