//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        public int bundle_id { get; set; }
        public string bundle_name { get; set; }
        public int corporate_id { get; set; }
    
        public virtual Corporate Corporate { get; set; }
    }
}
