//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FYPTLYEntities : DbContext
    {
        public FYPTLYEntities()
            : base("name=FYPTLYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Bundle> Bundles { get; set; }
        public virtual DbSet<Corporate> Corporates { get; set; }
        public virtual DbSet<Corporate_has_Patient> Corporate_has_Patient { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<HR_Contact_List> HR_Contact_List { get; set; }
        public virtual DbSet<Lab_results> Lab_results { get; set; }
        public virtual DbSet<Medical_Test> Medical_Test { get; set; }
        public virtual DbSet<Medical_Test_has_Lab_results> Medical_Test_has_Lab_results { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Question_Category> Question_Category { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_has_Patient> Staff_has_Patient { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<Survey_has_Questions> Survey_has_Questions { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
    }
}
