//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Medical_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_Test()
        {
            this.Medical_Test_has_Lab_results = new HashSet<Medical_Test_has_Lab_results>();
            this.Questions = new HashSet<Question>();
            this.Surveys = new HashSet<Survey>();
        }


        [Display(Name = "Medical Test ID")]
        [Required(ErrorMessage = "Please enter Medical test ID")]
        public int Medical_Test_id { get; set; }


        [Display(Name = "Test Name")]
        [Required(ErrorMessage = "Please enter Test Name")]
        public string test_name { get; set; }

        [Display(Name = "Test Description")]
        [Required(ErrorMessage = "Test Description")]
        public string test_description { get; set; }
        public int Staff_id { get; set; }
        public int appointment_id { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Test_has_Lab_results> Medical_Test_has_Lab_results { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
