//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Corporate_has_Patient = new HashSet<Corporate_has_Patient>();
            this.Staff_has_Patient = new HashSet<Staff_has_Patient>();
        }
    
     [Key]
        [Display(Name = "Patient ID")]
        public int Patient_id { get; set; }

        [Display(Name = "NRIC")]
        [RegularExpression(@"[STFG]\d{7}[A-Z]"),Required(ErrorMessage = "Please enter your NRIC")]
        
        public string Nric { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please enter your full name")]
        public string p_name { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "Please enter your address")]
        public string p_address { get; set; }

        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Please select gender")]

        public string p_gender { get; set; }

        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Please enter a valid Date of Birth")]
        public System.DateTime p_dob { get; set; }
 

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please enter a valid email address")]
        [EmailAddress]
        public string p_email { get; set; }

        [Display(Name = "Postal Code")]
        [Required(ErrorMessage = "Please enter a valid postal code")]
        public int postal_code { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Corporate_has_Patient> Corporate_has_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_has_Patient> Staff_has_Patient { get; set; }
    }
}
