//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Survey_has_Questions = new HashSet<Survey_has_Questions>();
        }

        [Display(Name = "Question ID")]
        [Required(ErrorMessage = "Please enter Question ID")]
        public int questions_id { get; set; }

        [Display(Name = "Question Text")]
        [Required(ErrorMessage = "Please enter Question Text")]
        public string question_text { get; set; }

        [Display(Name = "MCQ")]
        [Required(ErrorMessage = "Please enter MCQ")]
        public string mcq { get; set; }

        [Display(Name = "Question Option")]
        [Required(ErrorMessage = "Please enter Question Option")]
        public string question_option { get; set; }
        public int Question_Category_id { get; set; }
        public int Medical_Test_Medical_Test_id { get; set; }

        public virtual Medical_Test Medical_Test { get; set; }
        public virtual Question_Category Question_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey_has_Questions> Survey_has_Questions { get; set; }
    }
}
