//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Survey_has_Questions
    {

        [Display(Name = "Question")]
        [Required(ErrorMessage = "Please enter Question ID")]
        public int questions_id { get; set; }

        [Display(Name = "Survey ID")]
        [Required(ErrorMessage = "Please enter Survey ID")]
        public int Survey_id { get; set; }


        [Display(Name = "Answer")]
        [Required(ErrorMessage = "Please enter answer")]
        public string answer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
