//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTLY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.Survey_has_Questions = new HashSet<Survey_has_Questions>();
        }
        [Display(Name = "Survey ID")]
        public int survey_id { get; set; }

        [Display(Name = "Survey Name")]
        [Required(ErrorMessage = "Please enter Survey Name")]
        public string survey_name { get; set; }


        [Display(Name = "Date Conducted")]
        [Required(ErrorMessage = "Please enter the date conducted for the survey")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime date_conducted { get; set; }
        public int Medical_Test_id { get; set; }


        public virtual Medical_Test Medical_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey_has_Questions> Survey_has_Questions { get; set; }
    }
}
